# Generated by Django 4.1.4 on 2022-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='active',
            field=models.BooleanField(choices=[('active', 'active'), ('deactivate', 'deactivate')], null=True),
        ),
    ]
