# Generated by Django 4.1.4 on 2022-12-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0002_sprint_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='active',
            new_name='status',
        ),
    ]
