# Generated by Django 4.1.4 on 2022-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0003_rename_active_sprint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.BooleanField(choices=[('active', 'active'), ('deactivate', 'deactivate')], default=True),
        ),
    ]
