# Generated by Django 4.1.4 on 2022-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0004_alter_sprint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='status',
        ),
        migrations.AddField(
            model_name='sprint',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
