# Generated by Django 4.1.4 on 2022-12-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0006_remove_task_sprint_sprint_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastsprintapp.sprint'),
        ),
    ]
