# Generated by Django 4.1.4 on 2022-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastsprintapp', '0007_remove_sprint_tasks_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='preactivate',
            field=models.BooleanField(default=False),
        ),
    ]
